### ISSUE TITLE
Missing tile in top left

### ISSUE THREAD

**Issue by KBoehme** [ponywolf/ponytiled#1]
Following the README.md I am getting a missing tile on the top left corner like so.

![screen shot 2016-12-01 at 10 24 47 pm](https://cloud.githubusercontent.com/assets/5375288/20823844/0baa04cc-b815-11e6-9b44-6be5539fca31.jpg)

**Comment by superqix** [comment]
Look at that... I'm sure it's a something in the rendering. I'll get to it this week.

**Comment by superqix** [comment]
Yep... I was skipping the first tile by starting at index[0] instead of index[1]. Fixed in last commit....
