### ISSUE TITLE
Replacement for  table.insert 

### ISSUE THREAD

**Issue by ldurniat** [ponywolf/ponytiled#14]
Hi,

You could replace lines 74, 94 and 95 from[ ponytiled.lua](https://github.com/ponywolf/ponytiled/blob/master/com/ponywolf/ponytiled.lua)
```
local gid = 0
...
gid = gid + 1
table.insert( frames, gid, element ) 
```
with
`frames[#frames + 1] = element`

It doesn't change how ponytiled work but you gain a bit of speed:)

Have a nice day:)

ldurniat

**Comment by superqix** [comment]
Always love to simplify things....
