### ISSUE TITLE
Directory for tiled layer

### ISSUE THREAD

**Issue by agershun** [ponywolf/ponytiled#15]
I tried to use the library for tiled layer, but found that it can not find image files.

After some research I found that ponytiled doesnot specify directory name.

I fixed it in the file ```ponytiled.lua``` near the line 153 with ```dir ... gid```:
```lua
local image = sheet and display.newImage(objectGroup, sheet, gid, 0, 0) 
      or display.newImage(objectGroup, dir .. gid, 0, 0)
```

**Comment by ldurniat** [comment]
Hi @agershun ,

I have noticed this also. I proposed simple solution. See [Incorrect path for tiles on Tile Layer]( https://github.com/ponywolf/ponytiled/issues/13)

Have a nice day:)

ldurniat

**Comment by agershun** [comment]
Ops.. Sorry for duplication. Thank you!

**Comment by superqix** [comment]
Fixed with your solution. Sorry for the delay... I almost never use tile-sets.
