### ISSUE TITLE
Error in Simulator on line 214: 'end' expected near 'elseif'

### ISSUE THREAD

**Issue by ldurniat** [ponywolf/ponytiled#16]
Hi,

with the latest version of ponytiled I get error : 

.../ponytiled.lua: :214'end' expected (to close 'for' at line 194) near 'elseif'

I noticed that if I comment out lines 307,289,271 and 236 everything works fine:)

Have a nice day:)

ldurniat

**Comment by superqix** [comment]
should be fixed now
