### ISSUE TITLE
Broken logic trying to change empty string values into nil

### ISSUE THREAD

**Issue by bjorn** [ponywolf/ponytiled#17]
I noticed a broken logic used twice in the following code:

https://github.com/ponywolf/ponytiled/blob/457a262d3586c1ae85e2054298aa22d335ed304f/com/ponywolf/ponytiled.lua#L26-L38

If you write `v == "" and nil or v `, the returned value will always be `v`. If you really want an empty string to turn into nil, then it can be written like `v ~= "" and v or nil` (though that has the side-effect of turning `false` into `nil` as well, which is usually not a problem in Lua of course).

I wonder a little about why this is done though. I guess it is meant to make it easier to check for an empty property value, but then again since it wasn't working there is probably no code relying on this behavior?

**Comment by superqix** [comment]
I think my intent was if a value was an empty string then it should return a nil so it got caught by garbage collection.  Seems like a workable fix you've proposed... Although I do want to keep "false" separate from "nil" so I'll double check for that too.

Thanks for taking a peek.

**Comment by bjorn** [comment]
> I think my intent was if a value was an empty string then it should return a nil so it got caught by garbage collection.

Ah, if that was the reason I think you can just drop it, because strings in Lua are internally shared, so all those empty string values are going to be referencing the same small string instance. Nothing to gain by trying to get the garbage collector to clean that up.

So I'd suggest just doing `t[properties[i].name] = properties[i].value` and `image[k] = v` in that case.

**Comment by superqix** [comment]
Fixed with c62ca86
