### ISSUE TITLE
toBack overloaded

### ISSUE THREAD

**Issue by kingoftheconnors** [ponywolf/ponytiled#19]
When I tried using toBack, I got this error:

attempt to call method "toBack" (a boolean value)

Changing the "toBack" boolean variable to "pushBack" fixes the problem. "toBack" is just overloaded.

**Comment by superqix** [comment]
I don't see where toBack is a variable...

**Comment by kingoftheconnors** [comment]
Sorry. It's in the sort method in ponytiled.lua

**Comment by superqix** [comment]
So, toBack() is a function that get's called for the sorting to work. I test it first but seeing if it exists--that is that code block. 

I bet what's happening to you is one of your objects has a property called toBack that overwrote the function. If you change the sorting code it will for sure break sorting...

Good luck!

**Comment by superqix** [comment]
I should mention that .toBack() id a coronaSDK function that pushes an object to the back of a group, not a ponytiled function persay.

**Comment by kingoftheconnors** [comment]
I see. Thank you!
