### ISSUE TITLE
Tilelayer not displaying

### ISSUE THREAD

**Issue by jwheat** [ponywolf/ponytiled#2]
Thanks for posting this, its fantastic.
I saw in the readme that it mentions it  supports object layers and tile layers.

Is there a trick to get it to load a tilelayer?  I can only get it working with an object layer.
I've tried tilesheets from images and from a spritesheet.

I looked in the exported .lua file and it looks like its correct

```   layers = {
    {
      type = "tilelayer",
      name = "Tile Layer 1",
      x = 0,
      y = 0,
      width = 21,
      height = 26,
      visible = true,
      ...
```

any ideas?
-Jon

**Comment by superqix** [comment]
What directory do you have the map and spritesheet in? You may have to specify a directory. Try uncommenting Demo 1 from the main.lua and see if that works for you. It's a tilelayer map.

**Comment by superqix** [comment]
Also, Tile layer encoding/compression not supported. You will need to choose CSV or XML in Tiled's map options when you create a new map.
 
![screen shot 2016-12-05 at 7 59 32 am](https://cloud.githubusercontent.com/assets/717521/20889604/cd4f30ae-bac0-11e6-8017-2887680fa0fb.png)

**Comment by jwheat** [comment]
Ok, thank you. First, I changed to CSV for the map and followed the file locations in your demo keeping the .tmx and .json files in maps/tiles

and it works now, thanks
