### ISSUE TITLE
Does this loader work with Solar2D as well

### ISSUE THREAD

**Issue by bjorn** [ponywolf/ponytiled#20]
While updating a few things in the Tiled Manual, and I came upon this section:

> Maps and tilesets can be exported to Lua code. This export option supports most of Tiled’s features and is useful when using a Lua-based framework like LÖVE (with Simple Tiled Implementation), **Solar2D** (with **ponytiled** or Dusk Engine) or Defold.

It used to mention Corona SDK but I've updated it to mention Solar2D now. I would like to know whether the references to ponytiled (and Dusk Engine) are still valid. The latter appears to no longer be developed since 5 years so I'm guessing it might be better to remove it, but ponytiled still got some improvements last year.

So it is accurate to mention this loader along with Solar2D?

**Comment by superqix** [comment]
Yes, yes it does. 👍

**Comment by bjorn** [comment]
Alright, thanks for the confirmation! You may want to also update your `README.md` to mention Solar2D instead. :-)
