### ISSUE TITLE
Image tiles causing error

### ISSUE THREAD

**Issue by jwheat** [ponywolf/ponytiled#3]
Yea! I get to contribute something!

I found with a Tileset that contains images, the directory was not getting applied.

I have a .tmx, .json and .jpgs in the maps/tiles directory.  When the json is loaded, the following error occurs.

> Attempt to index local 'image' (a nil value)
> File: com/ponywolf/ponytiled.lua
> Line: 148
>stack traceback:
>	com/ponywolf/ponytiled.lua:148: in function 'new'
>	main.lua:23: in main chunk

I fixed this by changing line 146 in ponytiled.lua to this 

`local image = sheet and display.newImage( objectGroup, sheet, dir .. gid, 0, 0 ) or display.newImage( objectGroup, dir .. gid, 0, 0 )
`

adding the **dir ..**  before both **gid** instances

Now my map loads with image tiles.

Let me know if you'd prefer me to issue a pull request.

-Jon

**Comment by superqix** [comment]
Nice catch. I assume it's because the directory was baked into the GID. I went ahead and made the change, pushed and gave you the credit in the comment :)

**Comment by asmar1x** [comment]
I recently downloaded the .zip, and I had to make the same change on line 157.  Was the fix undone on another merge?

**Comment by superqix** [comment]
I think this issue is LUA vs. JSON loading... I really need to dig into this at some point. :)
