### ISSUE TITLE
"Background" Tiles don't line up with Objects

### ISSUE THREAD

**Issue by asmar1x** [ponywolf/ponytiled#4]
I tried a simple map, and I found that the tile layer is shifted to the left compared to the object layer(s).  I traced it back to ponytiled.lua line 159.

`image.x, image.y = (tx-1) * data.tilewidth, (ty+1) * data.tileheight`

![tiles1](https://cloud.githubusercontent.com/assets/19752013/23090554/7c18a358-f56e-11e6-9383-481c756dde65.png)

I'm not sure what the purpose of tx-1 is, but removing the -1 aligns the tiles with the objects.

![tiles2](https://cloud.githubusercontent.com/assets/19752013/23090553/7c0bee6a-f56e-11e6-8a1f-5c34f09350f3.png)

**Comment by ldurniat** [comment]
I think that @asmar1x  is right:)

**Comment by superqix** [comment]
Implemented
