### ISSUE TITLE
tile images not loading, ellipses showing as squares, can't load json

### ISSUE THREAD

**Issue by jesperp** [ponywolf/ponytiled#5]
Hi,
So there seems to be a bunch of errors, probably because of outdated code.

- [ ] Cannot load JSON data
- [ ] Image tiles not showing (object layer)
- [ ] Ellipses show up as squares 

I [created a repo](https://github.com/jesperp/simple-tiles) with as simple code as possible, it includes a spritesheet, tileset and a simple map with 3x3 squares.

Using:
- Tiled 1.0.2
- Ponytail, latest clone from github
- Corona Simulator 2017.3068 (2017.3.31)
- Lua 5.2.4

![screen shot 2017-08-08 at 10 24 26](https://user-images.githubusercontent.com/376921/29063787-46b301f0-7c27-11e7-86b2-d0807de1ecfb.png)

Only polygon is showing correctly:

![screen shot 2017-08-08 at 10 28 53](https://user-images.githubusercontent.com/376921/29064003-e7dc70a2-7c27-11e7-8928-c02a1ac0ade5.png)

And this is the error I get when trying to load a JSON export:

![screen shot 2017-08-08 at 10 26 52](https://user-images.githubusercontent.com/376921/29064017-f91b6bde-7c27-11e7-8d74-4e73d495f9c4.png)

**Comment by jesperp** [comment]
others have had the same issue:

https://forums.coronalabs.com/topic/69760-ludum-fail-loading-tiled-maps-am-i-being-daft/

Solved by downgrading Tiled to 0.18 but would be nice to use the new 1.0.2...

**Comment by superqix** [comment]
I don't know what is going on with the circle, but the main issue is that Ponytiled (as of right now) doesn't support external tile sets. You can create a an embedded tileset in 1.02 and most everything will work...

![screen shot 2017-08-08 at 9 33 23 am](https://user-images.githubusercontent.com/717521/29080345-c5605c24-7c1c-11e7-8158-272042f64556.png)

**Comment by jesperp** [comment]
ok! Now loading from JSON works (but not from Lua export), that should keep me going for a while.
Yeah, the circle-square is weird but I wont need it for now.. thanks!
