### ISSUE TITLE
Format of background color of map

### ISSUE THREAD

**Issue by ldurniat** [ponywolf/ponytiled#7]
Hi,

why do you check type of  `backgroundcolor` property of map (line 384) since according to [documentations](http://doc.mapeditor.org/en/latest/reference/json-map-format/#map) it may use `#AARRGGBB` or `#RRGGBB` format? Does this is due to format of map (lua or json) as input?

Have a nice day:)

**Comment by superqix** [comment]
This is for old Tiled version support.
